services:
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    networks:
      - habit-net
  sql_habit:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_habit
    environment:
      SA_PASSWORD: Tranleminh305@
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - habit-net
    volumes:
      - sql_data:/var/opt/mssql

  mongo_habit:
    image: mongo:6.0
    container_name: mongo_habit
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - habit-net
    volumes:
      - mongo_data:/data/db
  
  userservice:
    build: ./src/UserService
    container_name: userservice
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - sql_habit
  teamservice:
    build: ./src/TeamService
    container_name: teamservice
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - sql_habit
  taskservice:
    build: ./src/TaskService
    container_name: taskservice
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - sql_habit
  stickerservice:
    build: ./src/StickerService
    container_name: stickerservice
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - sql_habit
  shareservice:
    build: ./src/ShareService
    container_name: shareservice
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - sql_habit
  proofservice:
    build: ./src/ProofService
    container_name: proofservice
    ports:
      - "5006:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - mongo_habit
  notificationservice:
    build: ./src/NotificationService
    container_name: notificationservice
    ports:
      - "5007:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - sql_habit
  leaderboardservice:
    build: ./src/LeaderboardService
    container_name: leaderboardservice
    ports:
      - "5008:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - sql_habit
  friendservice:
    build: ./src/FriendshipService
    container_name: friendservice
    
    ports:
      - "5009:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - sql_habit
  chatservice:
    build: ./src/ChatService
    container_name: chatservice
    ports:
      - "5010:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - mongo_habit
  assignmentservice:
    build: ./src/AssignmentService
    container_name: assignmentservice
    ports:
      - "5011:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - sql_habit
  apigateway:
    build: ./src/ApiGateway
    container_name: apigateway
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - habit-net
    depends_on:
      - consul



  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo_habit
    depends_on:
      - mongo_habit
    networks:
      - habit-net
 


volumes:
  sql_data:
  mongo_data:

networks:
  habit-net:
    driver: bridge


